# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.3.0", "< 3.4.0"

gem "sinatra", "~> 4.0"
gem "rack", "~> 3.1"
gem "puma", "~> 6.4"
gem "rack-cors", "~> 2.0"
gem "mongo", "~> 2.20"
gem "redis", "~> 5.2"
gem "nats-pure", "~> 2.4"
