FROM node:20-slim AS base
RUN corepack enable

FROM base AS deps
WORKDIR /app

COPY . .

# IMPORTANT: install with workspaces
RUN npm install --workspaces

FROM deps AS builder
WORKDIR /app

RUN npm run build --workspace=web

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/web/public ./apps/web/public
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "apps/web/server.js"]